name: Build Writerside docs using Docker
description: Build Writerside documentation artifacts
author: writerside <writerside@jetbrains.com>
branding:
  icon: book-open
  color: purple

inputs:
  cli-version:
    description: 'The specific version of Writerside CLI to use'
    required: false
    default: '2.1.1322-p3476'

runs:
  using: 'composite'
  steps:
    - name: Build with Writerside CLI
      run: |
        docker run registry.jetbrains.team/p/writerside/builder/writerside-builder:${{ inputs.cli-version }} \
        '/opt/builder/bin/idea.sh helpbuilderinspect -source-dir . -product $PRODUCT --runner github -output-dir artifacts/ || true'





