name: Build Writerside docs using Docker
description: Build Writerside documentation artifacts
author: writerside <writerside@jetbrains.com>
branding:
    icon: book-open
    color: purple

inputs:
  docker_version:
    description: 'The Docker version to use for building the image'
    required: false
    default: '2.1.1279-p3399'

runs:
  using: 'docker'
  image: 'Dockerfile'
