name: Build Writerside docs using Docker
description: Build Writerside documentation artifacts
author: writerside <writerside@jetbrains.com>
branding:
    icon: book-open
    color: purple

inputs:
  docker-version:
    description: 'The version of the Docker image to use'
    required: false
    default: '2.1.1256-p3333'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--build-arg=DOCKER_VERSION=${{ inputs.docker-version }}'
