name: Build Writerside docs using Docker
description: Build Writerside documentation artifacts
author: writerside <writerside@jetbrains.com>
branding:
    icon: book-open
    color: purple

inputs:
    image-version:
        description: 'Writerside docker image version'
        required: false
    instance:
        description: "Module name and instance ID"
        required: true
    artifact:
        description: "Archive to store as artifact"
        required: true

runs:
    using: 'node16'
    main: 'dist/index.js'