name: Build Writerside docs using Docker
description: Build Writerside documentation artifacts
author: writerside <writerside@jetbrains.com>
branding:
    icon: book-open
    color: purple

inputs:
    docker-version:
        description: 'Writerside docker image version'
        required: false
    location:
        description: 'Writerside documentation module location'
        default: ''
        required: false
    instance:
        description: "Module name and instance ID"
        required: true
    artifact:
        description: "Archive to store as artifact"
        required: false
    pdf:
        description: "Generate PDF as artifact"
        required: false
    workingDirectory:
        description: "The directory inside the Writerside container where source files and artifacts will be processed"
        required: false
    container:
        description: "The name of an existing container whose volumes will be mounted for use in the current process"
        required: false
    is-group:
        description: "Build multi-instance group"
        required: false

runs:
    using: 'node20'
    main: 'dist/index.js'